language: node_js
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
env:
  - CXX=g++-4.8
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
before_script:
  - psql -c 'create database massive;' -U postgres
